

#include "NeighborList.cuh"
#include "AllInfo.cuh"
#include "saruprngCUDA.h"


#ifndef __POLYMERIZATION_CUH__
#define __POLYMERIZATION_CUH__



cudaError_t gpu_FRP_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_react_list,						
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_reaction_times,
					unsigned int* d_is_init,
					unsigned int Np,
					unsigned int new_bond_type,
					unsigned int* d_change_type,					
					int blocksize);
					
cudaError_t gpu_exchange_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_react_list,						
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_is_init,
					unsigned int* d_maxcris,
					unsigned int Np,
					unsigned int* d_change_type,					
					int blocksize);

cudaError_t gpu_SGAP_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_react_list,						
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_is_init,					
					unsigned int* d_maxcris,
					unsigned int Np,
					unsigned int new_bond_type,
					unsigned int* d_change_type,					
					int blocksize);

cudaError_t gpu_insertion_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_react_list,						
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_is_init,
					unsigned int* d_maxcris,
					unsigned int Np,
					unsigned int new_bond_type,
					unsigned int* d_change_type,					
					int blocksize);						
#endif


