#include "NeighborList.cuh"
#include "AllInfo.cuh"
#include "saruprngCUDA.h"


#ifndef __POLYMERIZATION_DIS_CUH__
#define __POLYMERIZATION_DIS_CUH__



cudaError_t gpu_FRP_Dis_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_reaction_times,
					unsigned int* d_init,
					unsigned int Np,
					unsigned int new_bond_type,	
					unsigned int* d_change_type,					
					int blocksize);
					
cudaError_t gpu_exchange_Dis_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_init,
					unsigned int* d_maxcris,
					unsigned int Np,
					unsigned int* d_change_type,					
					int blocksize);

cudaError_t gpu_SGAP_Dis_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_init,					
					unsigned int* d_maxcris,
					unsigned int Np,
					unsigned int new_bond_type,	
					unsigned int* d_change_type,					
					int blocksize);

cudaError_t gpu_FRP_Func_compute(Real4* d_pos,
					unsigned int* d_tag,
					unsigned int* d_rtag,
					const gpu_boxsize &box, 
					const unsigned int *d_n_neigh,
					const unsigned int *d_nlist,
					const Index2D& nli,
					unsigned int* d_react_list,						
					unsigned int* d_n_tag_bond,
					uint2* d_tag_bonds,
					unsigned int* d_n_idx_bond,
					uint2* d_idx_bonds,
					unsigned int pitch,
					unsigned int *d_cris,
					unsigned int seed,
					Real rcutsq,
					unsigned int coeff_width,
					Real2* d_pr,
					unsigned int* h_ninit,
					unsigned int* d_ninit,
					unsigned int* d_init_group,
					unsigned int* d_reaction_times,
					unsigned int* d_init,
					unsigned int Np,
					unsigned int new_bond_type,
					Real4 func_params,
					int func_id,
					Real T,
					unsigned int* d_change_type,					
					int blocksize);				
					
					
cudaError_t gpu_SGAP_Func_compute(Real4* d_pos,
							unsigned int* d_tag,
							unsigned int* d_rtag,
							const gpu_boxsize &box, 
							const unsigned int *d_n_neigh,
							const unsigned int *d_nlist,
							const Index2D& nli,
							unsigned int* d_react_list,								
							unsigned int* d_n_tag_bond,
							uint2* d_tag_bonds,
							unsigned int* d_n_idx_bond,
							uint2* d_idx_bonds,
							unsigned int pitch,
							unsigned int *d_cris,
							unsigned int seed,
							Real rcutsq,	
							unsigned int coeff_width,
							Real2* d_pr,
							unsigned int* h_ninit,
							unsigned int* d_ninit,
							unsigned int* d_init_group,
							unsigned int* d_init,					
							unsigned int* d_maxcris,
							unsigned int Np,
							unsigned int new_bond_type,
							Real4 func_params,
							int func_id,
							Real T,	
							unsigned int* d_change_type,							
							int blocksize);

cudaError_t gpu_exchange_Func_compute(Real4* d_pos,
							unsigned int* d_tag,
							unsigned int* d_rtag,
							const gpu_boxsize &box, 
							const unsigned int *d_n_neigh,
							const unsigned int *d_nlist,
							const Index2D& nli,
							unsigned int* d_react_list,								
							unsigned int* d_n_tag_bond,
							uint2* d_tag_bonds,
							unsigned int* d_n_idx_bond,
							uint2* d_idx_bonds,
							unsigned int pitch,
							unsigned int *d_cris,
							unsigned int seed,
							Real rcutsq,
							unsigned int coeff_width,
							Real2* d_pr,
							unsigned int* h_ninit,
							unsigned int* d_ninit,
							unsigned int* d_init_group,
							unsigned int* d_init,
							unsigned int* d_maxcris,
							unsigned int Np,
							Real4 func_params,
							int func_id,
							Real T,	
							unsigned int* d_change_type,							
							int blocksize);							
										
#endif


